//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace net48_mvc.Entities
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class pegawai_tbl
    {
        [Required]
        public System.Guid ID { get; set; }
        [Required]
        public string NAMA { get; set; }
        [Required]
        public string EMAIL { get; set; }
        [Required]
        public Nullable<int> GENDER { get; set; }
        [Required]
        public Nullable<int> HOBY { get; set; }
        [Required]
        public string NIP { get; set; }
    }
}
